const { zokou } = require("../framework/zokou");
const { conf } = require("../set"); // Ensure your settings file is correctly linked
const moment = require("moment-timezone");

zokou({
  name: "menu",
  alias: ["h", "help", "list"],
  category: "General",
  reaction: "📑"
}, async (dest, zk, reponce) => {
  const { ms, pushName, sender } = reponce;
  
  // 1. Fetch all registered commands from the framework
  const { commands } = require("../framework/zokou");
  
  // 2. Set Time and Date based on configuration
  const time = moment().tz(conf.TZ || "Africa/Nairobi").format("HH:mm:ss");
  const date = moment().tz(conf.TZ || "Africa/Nairobi").format("DD/MM/YYYY");

  // 3. Fetch User Profile Picture
  let profilePic;
  try {
    profilePic = await zk.profilePictureUrl(sender, 'image');
  } catch (e) {
    // Default image if user has no profile pic or privacy settings block it
    profilePic = "https://telegra.ph/file/8bc900f074d0928e46123.jpg"; 
  }

  // 4. Organize Commands into Categories
  const categorized = {};
  commands.forEach(cmd => {
    if (!categorized[cmd.category]) {
      categorized[cmd.category] = [];
    }
    categorized[cmd.category].push(cmd.name);
  });

  // 5. Build the Menu String
  let menuHeader = `
╭━━━〔 *${conf.BOT_NAME || "TIMNASA-TXMD"}* 〕━━━┈⊷
┃ 👤 *User:* ${pushName}
┃ 🕰️ *Time:* ${time}
┃ 📅 *Date:* ${date}
┃ 🛸 *Total Commands:* ${commands.length}
┃ 📡 *Status:* Online
╰━━━━━━━━━━━━━━━━━━┈⊷\n`;

  let menuBody = "";
  // Sort categories alphabetically and list their commands
  Object.keys(categorized).sort().forEach(cat => {
    menuBody += `\n┏━━━ *〔 ${cat.toUpperCase()} 〕* ━━━┈⊷\n`;
    categorized[cat].forEach(name => {
      menuBody += `┃ ◈ .${name}\n`;
    });
    menuBody += `┗━━━━━━━━━━━━━━━━━━┈⊷\n`;
  });

  const footer = `\n__________________________________
*©${new Date().getFullYear()} ${conf.OWNER_NAME || "Timoth Timnasa"}*
*Generated by Zokou Auto-Menu*`;

  // 6. Send the Menu with the User's Profile Picture
  await zk.sendMessage(dest, {
    image: { url: profilePic },
    caption: menuHeader + menuBody + footer,
    contextInfo: {
      externalAdReply: {
        title: "DYNAMIC COMMAND PANEL",
        body: `Hello ${pushName}, here is your automated command list.`,
        thumbnailUrl: profilePic,
        sourceUrl: "https://whatsapp.com/channel/0029VajweHxKQuJP6qnjLM31",
        mediaType: 1,
        renderLargerThumbnail: false,
        showAdAttribution: true
      }
    }
  }, { quoted: ms });
});
